### ISSUE TITLE
not invalid style in tel input 

### ISSUE THREAD

**Issue by Mohammadgeek** [Mohammadgeek/loginfourm#1]
https://github.com/Mohammadgeek/loginfourm/blob/3a3b8ac036b793a41abfd0f07d729c1164897f8d/css/dynamic.css#L111

توی کد بالا هر کاری میکنم اون قسمت ورودی تلفن استایل نمی گیره دلیل اش چیه ؟

**Comment by CyrusKabir** [comment]
سلام رفیق. امکانش هست بیشتر درباره این مشکل توضیح بدید ؟

**Comment by CyrusKabir** [comment]
مشکل رو تونستم حل کنم و یه چیزی جدید هم یاد گرفتم و فهمیدم درباره رفتار و ویژگی required که قبلا نمیدونستم. وقتی که این وِیژگی روی یک input گذاشته میشه و اگه اون input  یک مقدار خالی یا empty string داشته باشه اون رو به عنوان یک input نامعتبر یا invalid در نظر  میگیره. که در این صورت میشه اون رو با شبه انتخابگر :invalid انتخاب کرد. input شماره تلفن تنها input بود که ویژگی required نداشت و استایل مربوط به valid رو میگرفته.

**Comment by CyrusKabir** [comment]
لینک های مرتبط با این موضوع :
 [HTML required attribute](https://html.spec.whatwg.org/#the-required-attribute)
[MDN required_constraint-validation](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required#constraint_validation)

**Comment by Mohammadgeek** [comment]
@CyrusKabir مرسی ازت 🙃
