### ISSUE TITLE
span style item when user backpage

### ISSUE THREAD

**Issue by Mohammadgeek** [Mohammadgeek/loginfourm#3]
سلام اون قسمت span وقتی کاربر backpage میزنه و دوباره برمیگرده توی منوی ثبت نام استایل اش بهم میزره از ساختار for of خواستم استفاده کنم ولی ایجاد نمیشه 
https://github.com/Mohammadgeek/loginfourm/blob/2737830063f35e0e1e6e3d7372f114860b808f36/js/main.js#L39

**Comment by CyrusKabir** [comment]
هیچ ربطی به این قسمت از کدت نداره. فرم ثبت نامت در حالت عادی رو حالت نمایش display:flex، قرار داره. ولی بعد از رفتن به فرم ورود و برگشت حالت نمایش اون میشه display:block
